### ISSUE TITLE
that error in doing spark-submit last stage?

### ISSUE THREAD

**Issue by aifreak00** [tejasjbansal/Realtime-Scalable-Data-Engineering-Pipeline-#1]
the error is coming in doing spark-submit can you please fix it...... or tell me how to proceed that in last step

**Comment by tejasjbansal** [comment]
@aifreak00, please change the local host to container names of Cassandra and kafka connection in spark file. And then submit the job again

OR

Just run the python spark_stream.py.

**Comment by aifreak00** [comment]
it worked thanks?
